version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:19.10
   steps:
      - run:
          command: |
           apt -y update && apt -y install lrzip
           wget https://raw.githubusercontent.com/CurioussX13/.circleci/master/.circleci/build.sh
           sh build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
